### ISSUE TITLE
CJK characters not shown when using non-CJK font

### ISSUE THREAD

**Issue by yiding-he** [neoedmund/neoeedit#1]
![批注 2019-12-05 113833](https://user-images.githubusercontent.com/900606/70202185-e0d4fa80-1753-11ea-9048-9dd426e49cf8.png)
We need a default JCK font（embedded or search for the OS）to display CJK characters.

**Comment by neoedmund** [comment]
It is strange, this is because the default font for the Windows system or JDK is not correctly set.
For a workaround, you can press `alt-f` to see all the fonts, then use `ctrl-1` on the line of the font you want to use. If you font is okay, you can locate the font file's path and set it in the config file `{home}/.neoeedit/data.py.verXX` in the font section.

**Comment by neoedmund** [comment]
---update--- I see your use-case.

> In the config file, font section, the font files are a list, characters will be rendered in order using the first found in a font file.

 It is so designed and once so implemented, but for performance reason, now only the first font is used. so the answer currently is `no, you can't. ` 
however, If anyone want to hack the code, see code near U.java(Line:183)

**Comment by yiding-he** [comment]
After some trying, I think what it needs is more likely a refactoring, rather than a hacking: https://github.com/yiding-he/neoeedit/commit/46398999f0b85ca37df0e8aae44373aed738a94c

This is a half-done fix, and... I gave up.

**Comment by neoedmund** [comment]
> After some trying, I think what it needs is more likely a refactoring, rather than a hacking: [yiding-he@4639899](https://github.com/yiding-he/neoeedit/commit/46398999f0b85ca37df0e8aae44373aed738a94c)
> 
> This is a half-done fix, and... I gave up.

Nice try.  ;-)
One way is to cache the info about whether a char is contained in a font. `Font.canDisplayUpTo()` has performance issue, it should be a bug of JDK. 
Some CJK font  also has good-looking English char, so I not bother to include complex code for workaround for   `Font.canDisplayUpTo()` 
Keep simple is a key for neoeedit, so that it is still not a bloatware but slim after 10 years already passed.

**Comment by neoedmund** [comment]
@yiding-he 
I have made a fix for this, https://github.com/neoedmund/neoeedit/commit/219613ee820e41ce9799d32267887d06265059e4
Now support multi-font rendering.
You can check out the latest version.
Set your font in `[home]/.neoeedit/data.py.ver22`
If you find any problem, update this issue please.
